version: '3.4'

volumes:
  logs-data: {}


services:
  weatherforecast:
    image: ${DOCKER_REGISTRY-}weatherforecast
    build:
      context: .
      dockerfile: WeatherForecast/Dockerfile
    volumes:
      - /mnt/c/logs/:/logs
    ports:
      - "54935:80"
  
  #grafana-agent:
  #  image: grafana/agent:latest
  #  volumes:
  #    - ./grafana-agent-config.yaml:/etc/grafana-agent-config.yaml
  #  entrypoint:
  #    - /bin/agent
  #    - -config.file=/etc/grafana-agent-config.yaml
  #    - -metrics.wal-directory=/tmp/agent/wal
  #    - -enable-features=integrations-next
  #    - -config.expand-env
  #    - -config.enable-read-api
  #  environment:
  #    HOSTNAME: grafana-agent
  #    LOKI_HOST: loki:3100
  #    TEMPO_HOST: tempo:4317
  #  ports:
  #    - "12345:12345"
  #  depends_on:
  #    - loki
  #    - tempo

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /mnt/c/logs/:/logs
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      - "8125:8125"   #statsd
    depends_on:
      - loki
      - tempo
    
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:master
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
