receivers:
  filelog:
    include: [ /logs/otel-agent-test/nlog/**/*.log ]
    attributes:
      Application: weatherforecast
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'

  otlp:
    protocols:
      grpc:
  
  statsd:
    endpoint: "otel-collector:8125" # default
    aggregation_interval: 5s  
    enable_metric_type: false   # default
    is_monotonic_counter: false # default
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "histogram"
        histogram:
          max_size: 50
      - statsd_type: "timing"
        observer_type: "summary"

exporters:
  #logs
  logging:
    loglevel: debug
    
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
      
  file/logs:
    path: /logs/logs.json
    rotation:

  elasticsearch/logs:
    endpoints: [ http://input-loki-ibe-logstash.staging.d-edge.app:5140 ]
    logs_index: weatherforecast_log_index
    tls:
      insecure: true

  #metrics
  file/metrics:
    path: /logs/metrics.json

  #traces
  otlp/traces:
    endpoint: tempo:4317
    tls:
      insecure: true
      
processors:
  batch:
    timeout: 5s

  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: http.status_code

  resource:
    attributes:
    - action: insert
      key: loki.attribute.labels
      value: http.status
    - action: insert
      key: loki.resource.labels
      value: host.name

extensions:

service:
  extensions: 

  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [file/logs, elasticsearch/logs]
    metrics:
      receivers: [otlp, statsd]
      processors: [batch]
      exporters: [logging, file/metrics]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/traces]
